### PR TITLE
Update DI Incubator Project and Homepage

### LINKED ISSUE #18: Update content on <Home>
**URL**
https://difund.herokuapp.com

**Content to be modified**

- Some typos in this copy; inconsistent use of the serial comma:

Digital infrastructure is the code, policies**,** and standards powering the technology that permeates every aspect of life, such as hospitals, banking**,** and social media.
This infrastructure is under-maintained and undermined in ways that often favor corporate and government interests over the needs of the public.

We’re creating a community of researchers an**d** practitioners to be**tter** understand the problem and to work together toward our common goal: a commons of technology, sustainably developed and maintained, for the benefit of everyone.
Our partners fund work in this space regularly**.** If you’d like to propose a project or join our funding partners**,** contact us using the form below, and we’ll be in touch.

- Can't see what kind of things you have in mind under "Events" but the Incubator is hosting an Event Series, _Building Laterally: Political Imagination to Support and Sustain Digital Infrastructure_ as part of that program. Would be very happy to have them included if it feels appropriate! More on the series is here: https://incubator.codeforscience.org/building-laterally
- We don't have resources yet but we plan to have them and will plan to share!

thank you!

### PR DESCRIPTION
**Pull request by BenJam**
Fixes #18 and #17 

credit: @rayelz

### CODE REVIEW

**Comment by RichardLitt** [comment]
- [ ] Add https://incubator.codeforscience.org/building-laterally events.

**Comment by RichardLitt** [comment]
@flickz Do you know why this failed to deploy?

**Review by RichardLitt — APPROVED** [review]

**Comment by flickz** [comment]
@RichardLitt I don't have access to the vercel deployment log.

**Comment by RichardLitt** [comment]
Me neither. Hmm. This looks fine to me! @BenJam Can you add @flickz and I to the Vercel team?

**Pull request merged**
