### PR TITLE
Add search, filter and sort to resources page and search for project page

### LINKED ISSUE #25: Rethink resources page
The resources page is already a little unruly: https://digitalinfrastructure.fund/resources/

We should probably rethink the indexing and findability here. One of the key requirements from Sloan's side was a single place to gather all the research in this space for easy browsing and retrieval. Ford broke things up by project https://www.fordfoundation.org/campaigns/critical-digital-infrastructure-research/  which works well, but we may also want to indicate new research too.

/cc @Memo-Es @flickz

### PR DESCRIPTION
**Pull request by flickz**
Resolves #25 and https://github.com/digitalinfrastructurefund/website/issues/33

### CODE REVIEW

**Comment by RichardLitt** [comment]
Thanks, @flickz. The filter doesn't seem to work; what am I missing? Nothing changes when I type something in. 

As well, there's only one type of resource. How do I add different types?

**Comment by flickz** [comment]
@RichardLitt I don't know the expected type of resources but if you want to add type to resources in a project, add a `type` property to the resource object. 

```js
export const resources = [
  {
    title: "Detecting At-Risk Software Infrastructure",
    link: "https://blog.communitydata.science/detecting-at-risk-software-infrastructure/",
    linkText: "Read More",
    author: "Kaylea Champion",
    type: ""
  },
];
```

What are the expected types? I need the list (`[]`) to implement the `type` filter which is what is currently missing.

**Comment by RichardLitt** [comment]
Thanks Olu. For now, why don't we add: `["website", "talk", "document"]`. I can add more as they come up - would it be possible to make the list of possible types dynamic based on the values of all of the type fields?

**Comment by flickz** [comment]
@RichardLitt Yes, it is possible. I've implemented it now. Go ahead and `type` field to the project resources. As an example of this, I added type for this project.

https://github.com/digitalinfrastructurefund/website/pull/28/commits/0dbd524f76785f5ae9eb20c6496671a509e068c4#diff-75fef3b4800bfdf98e11f7594deee6d79d4a0b7c52315179adf67a79a77d1cfb

**Comment by RichardLitt** [comment]
Looks great to me! Thank you, @flickz.

**Pull request merged**
